name: Build API

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.11 # or "latest", "canary", <sha>

      - name: Install dependencies
        run: bun i

      - name: API build
        run: bun run build

      - name: API build types
        run: bun run build:types
