name: Auto Merge

on:
  pull_request:
    types:
      - labeled

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Auto merge if labeled "ready"
      if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'ready')
      run: |
        # Add any additional checks you might need before merging
        # For example, running tests, linting, etc.
        
        # Merge the pull request
        gh pr merge --auto --merge --squash
