name: Auto Merge

on:
  pull_request:
    branches:
      - main
    types:
      - labeled

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Auto merge if labeled "ready"
      if: contains(github.event.pull_request.labels.*.name, 'ready')
      run: |
        gh pr merge --auto --merge --squash
