on:
  pull_request:
    types: [opened, reopened, labeled, edited]
  pull_request_review:
    types: [dismissed]
    required_labels:
      - ready
    blacklisted_labels:
      - ['[API] WIP', '[Shared] WIP', '[Web] WIP']
    
permissions:
  contents: read
  pull-requests: write
  
jobs:
  autoapproval:
    runs-on: ubuntu-latest
    name: Autoapproval
    steps:
      - uses: dkhmelenko/autoapproval@latest_version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
