name: Auto Approve

on:
  pull_request:
    types:
      - labeled

jobs:
  auto_approve:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Auto approve if labeled "ready"
      if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'ready')
      run: |
        # Add any additional checks you might need before approving
        # For example, checking the author, files modified, etc.

        # Approve the pull request using GitHub API
        PR_NUMBER=$(echo "${{ github.event.pull_request.url }}" | awk -F/ '{print $NF}')
        TOKEN=$GITHUB_TOKEN  # GITHUB_TOKEN is a built-in token provided by GitHub Actions

        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token $TOKEN" \
          https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/reviews \
          -d '{"event": "APPROVE"}'
