name: Build Shared

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-shared:
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: bun i

      - name: Shared build
        run: bun run build:shared
