name: Build API

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '43 23 * * 2'

jobs:
  build-api:
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: bun i

      - name: API build
        run: bun run build:api

      - name: API build types
        run: bun run build:api:types
